config/routes.rb
Rails.application.routes.draw do
  get 'palindromes', to: 'palindromes#index'
  get 'palindromes/calculate', to: 'palindromes#calculate'
  root 'palindromes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/palindromes_controller.rb
class PalindromesController < ApplicationController
  def index
  end

  def calculate
    n = params[:n].to_i
    @palindromes = palindrome_numbers(n)
  end

  private

  def palindrome_numbers(n)
    palindromes = []

    (1..n).each do |num|
      decimal_palindrome = num.to_s
      binary_palindrome = num.to_s(2)

      if decimal_palindrome == decimal_palindrome.reverse && binary_palindrome == binary_palindrome.reverse
        palindromes << { decimal: num, binary: binary_palindrome }
      end
    end

    palindromes
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Palindromes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/palindromes/calculate.html.erb
<h1>Palindrome Numbers</h1>

<table>
  <thead>
  <tr>
    <th>Decimal</th>
    <th>Binary</th>
  </tr>
  </thead>
  <tbody>
  <% @palindromes.each do |palindrome| %>
    <tr>
      <td><%= palindrome[:decimal] %></td>
      <td><%= palindrome[:binary] %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<%=link_to "repeat calculation", palindromes_path %>

app/views/palindromes/index.html.erb
<h1>Palindrome Numbers</h1>

<%= form_tag palindromes_calculate_path, method: :get do %>
  <%= label_tag :n, "Enter a value for n (n ≤ 10^6):" %>
  <%= text_field_tag :n %>
  <%= submit_tag "Calculate" %>
<% end %>